# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='example',
  syntax='proto3',
  serialized_options=b'\n\030io.grpc.examples.exampleB\013SampleProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csample.proto\x12\x07\x65xample\",\n\rSampleRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63lock\x18\x02 \x01(\x04\",\n\x0bSampleReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x65rcd\x18\x02 \x01(\t2J\n\rSampleService\x12\x39\n\x07Request\x12\x16.example.SampleRequest\x1a\x14.example.SampleReply\"\x00\x42/\n\x18io.grpc.examples.exampleB\x0bSampleProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_SAMPLEREQUEST = _descriptor.Descriptor(
  name='SampleRequest',
  full_name='example.SampleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='example.SampleRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clock', full_name='example.SampleRequest.clock', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=69,
)


_SAMPLEREPLY = _descriptor.Descriptor(
  name='SampleReply',
  full_name='example.SampleReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='example.SampleReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ercd', full_name='example.SampleReply.ercd', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['SampleRequest'] = _SAMPLEREQUEST
DESCRIPTOR.message_types_by_name['SampleReply'] = _SAMPLEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SampleRequest = _reflection.GeneratedProtocolMessageType('SampleRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLEREQUEST,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:example.SampleRequest)
  })
_sym_db.RegisterMessage(SampleRequest)

SampleReply = _reflection.GeneratedProtocolMessageType('SampleReply', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLEREPLY,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:example.SampleReply)
  })
_sym_db.RegisterMessage(SampleReply)


DESCRIPTOR._options = None

_SAMPLESERVICE = _descriptor.ServiceDescriptor(
  name='SampleService',
  full_name='example.SampleService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=117,
  serialized_end=191,
  methods=[
  _descriptor.MethodDescriptor(
    name='Request',
    full_name='example.SampleService.Request',
    index=0,
    containing_service=None,
    input_type=_SAMPLEREQUEST,
    output_type=_SAMPLEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAMPLESERVICE)

DESCRIPTOR.services_by_name['SampleService'] = _SAMPLESERVICE

# @@protoc_insertion_point(module_scope)
