ATHRILL_DIR			:=../../../athrill
CORE_DIR			:= $(ATHRILL_DIR)/src
APLDIR				:= $(ATHRILL_DIR)/apl


#
# Warning flags
#
WFLAGS			:= -g -Wall
WFLAGS			+= -Wunknown-pragmas
WFLAGS			+= -Wimplicit-int
WFLAGS			+= -Wtrigraphs
WFLAGS			+= -std=gnu99
WFLAGS			+= -mtune=native -march=native -mfpmath=both 

#
# Define flags
#
DFLAGS			:= -DOS_LINUX
DFLAGS			+= -DATHRILL_EXT_DEVICE

#
# compiler
#
GCC			:= gcc
AR			:= ar
RANLIB			:= ranlib
CP			:= /bin/cp
RM			:= /bin/rm

#
# AR flags
#
AFLAGS			:= -rcSv

DLFLAGS			:= -shared -fPIC


LFLAGS	:= -Wl,--allow-multiple-definition
LIBS	:= -lpthread 
LIBS	+= $(CAN_DBG_LIBS)

ifeq ($(gprof),true)
 include make_conf/gnu_profile.def
endif

.SUFFIXES:      .c .o

.c.o: 	$<
	$(GCC) -O3 -c $(CFLAGS) -fPIC $(DFLAGS) $<
